# -*-Makefile-*-

PROJ = blink_app
ROOTDIR = ../..

ASMSRCS += blink_dom.S
SRCS += blink.c 

include ../Makerules

vpath blink.c ../../modules/demos/blink/
vpath blink_dom.S ../../modules/demos/blink/

